### PR TITLE
View food feature

### PR DESCRIPTION
**Pull request by mosaab-ss**
Added react boiler plate
added material UI with basic UI features including header and sidebar
added basic view food results

### CODE REVIEW

**Comment by lexinelson** [comment]
Is there a route to access the food and restaurant search?  If so, should it be linked in the sidebar navigation right away or would it be better to only allow access for logged in users (as a default redirect, possibly)?

Secondly, will we be leaving the call to the mock API for merging to dev? It may be a good idea - given that our microservices haven't been migrated to cloud yet and it should be a simple enough hotfix later.

**Comment by mosaab-ss** [comment]
Adding a route to the side bar might be a good idea, I think in one of our planning sessions we discussed that we want unauthenticated users to be able to search for food as well, but when they place an order, they have to be authenticated.

As for the API call, I think it would be best to use the microservices URI, and if we're ever testing it independently, we can mock it on-the-fly.

**Comment by mosaab-ss** [comment]
Added route to search page from menu.
Added integration tests
Added pagination
Refactored filters to "better" enums

**Comment by mosaab-ss** [comment]
Ready for review

**Pull request merged**
